### ISSUE TITLE
backport makefile and cleanup changes from kas-fleet-manager

### ISSUE THREAD

**Issue by machi1990** [bf2fc6cc711aee1a0c2a/ffm-project#27]
### Description
Backport a few recent and worthwhile changes of the Makefile from the https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager repository
### Task List

- [ ] backport bumping to golang 1.19
- [ ] backport removal of go-bindata
- [ ] backport removal of GO111MODULE
- [ ] backport the additional of .dockerignore file
- [ ] backport update of several tooling dependencies in the Makefile
- [ ] etc
